
version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017 # puerto-pc:puerto-contenedor
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db # respaldo de la BD en mi pc local